@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"E:\IAR6.2\common\bin\cspybat" "E:\IAR6.2\arm\bin\armproc.dll" "E:\IAR6.2\arm\bin\armjlink.dll"  %1 --plugin "E:\IAR6.2\arm\bin\armbat.dll" --flash_loader "E:\IAR6.2\arm\config\flashloader\EnergyMicro\FlashEFM32.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "E:\IAR6.2\arm\CONFIG\debugger\EnergyMicro\EFM32G232F128.ddf" "--drv_verify_download" "--semihosting" "--device=EFM32G232F128" "--drv_communication=USB0" "--jlink_speed=auto" "--jlink_initial_speed=32" "--jlink_reset_strategy=0,0" "--jlink_interface=SWD" "--drv_catch_exceptions=0x000" "--drv_swo_clock_setup=72000000,1,2000000" 


